name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        run: mvn -B package --file pom.xml

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: RapidBow
          path: target/*.jar
